### PR TITLE
Add more file naming options

### PR DESCRIPTION
**Pull request by ktmii**
Thank you for making this awesome project!

This PR adds Apator Miitors ApS specific file namings for gerber files.

### CODE REVIEW

**Comment by ktmii** [comment]
Perhaps a more scalable solution would be to allow the user to enter custom search strings in the UI, which are then saved in the settings file,.

**Comment by dennevi** [comment]
Thank you for your contribution! I like that the list of filename patterns grows.

Yea, this could be made so much more customizable... I would also like it to be easier both for people to add filename patterns, and to commit them to the project.

**Comment by ktmii** [comment]
I think making a merge request is fine for contributions to the project itself - especially with this short of a response time 😄

**Comment by dennevi** [comment]
At least sometimes I'm quick 😄 Unfortunately a contribution to file patterns requires both a Github account and some git knowledge, but that will have to do for now. I'm putting minimal effort into this project. The few hours I have I rather use to develop a plugin to KiCad called Board2Pdf. 
https://gitlab.com/dennevi/Board2Pdf

**Pull request merged**
